### ISSUE TITLE
Loading images on Docker-based TissUUmaps

### ISSUE THREAD

**Issue by Mena-SA-Kamel** [TissUUmaps/TissUUmaps#10]
Hi all,

Thank you for the amazing tool you have created! I am trying to deploy TissUUmaps on a remote host using the Dockerfile that is provided. I am however not able to load image files (I am able to load markers however).

I came across [issue](https://github.com/TissUUmaps/TissUUmaps/issues/1#issue-1138977697) and I set `READ_ONLY = False` in container/tissuumaps.cfg

When I re-deploy the Docker image, and navigate to File>Open, I get a 404 error:

<img width="1728" alt="Screen Shot 2022-11-01 at 11 13 55 AM" src="https://user-images.githubusercontent.com/37190503/199267923-5fca68d8-14be-4dde-8af0-b35c501aed2e.png">

Is there a work around to enable TissUUmaps to load up images from local storage or perhaps S3 when TissUUmaps is deployed on a remote host?

**Comment by cavenel** [comment]
Hi,

That's weird, it seems like you are doing everything correctly to run TissUUmaps in Docker.
The "Open" modal is loading `/filetree/sfiles` url, could you check in the browser DevTools (F12 in Chrome) the Network tab, and see what it tries to load when you click on Open?
![image](https://user-images.githubusercontent.com/6164758/199279942-c87b6181-97c0-4124-975c-d95a47ba3eed.png)

**Comment by Mena-SA-Kamel** [comment]
Hi! Apologies for the very late reply. I was able to get around the issue by setting READ_ONLY = True, and storing all the images and .csvs under the container's /mnt/data/shared/ directory. 

Mena
