### ISSUE TITLE
Error during Points2Regions plugin

### ISSUE THREAD

**Issue by kaizen89** [TissUUmaps/TissUUmaps#16]
Hi there,
I'm trying to use the Points2Regions plugin on visium data.
I have installed tissuumaps in a conda environement on a mac. I have also installed sklearn, scikit-image and pandas.
When I try to run the plugin I get this error:
```This plugin only works on a pip installation of TissUUmaps, with the extra packages: pandas, sklearn, skimage```
Also, a side question, how does tissuumaps figure out which columns in my file correspond to genes/markers as I have other categorical variables in my csv file?
Thanks

**Comment by cavenel** [comment]
Hi @kaizen89,

If you run TissUUmaps from the terminal, can you copy here the error message in the terminal after you start the plugin? You may have to start TissUUmaps with the `--debug` option.

You should be able to select the column you want to use in the plugin directly.
But note that this plugin is designed for data with individual genes points (like FISH or ISS) more than for Visum data (with multiple genes expressed in each spot).
It should be possible to adapt to the second ones, but could be a bit of work on the plugin (tag @axanderssonuu who wrote the plugin)
