### ISSUE TITLE
Pre-load images to project with script?

### ISSUE THREAD

**Issue by andrewjUTSW** [TissUUmaps/TissUUmaps#17]
Dear Tissuumaps team,

First off, excellent tool you've built! Thank you.

Next, is there a way to setup images to be loaded into a project via a script so I don't have to manually  add them (this is especially useful when we have +30 markers)

Thanks!

**Comment by cavenel** [comment]
Hi,

The tmap project file is a simple json format. You can find the specs (not really up to date but should still work) [here](https://tissuumaps.github.io/TissUUmaps-docs/docs/advanced/tmap.html).
So you can absolutely add images in the json file with a script (e.g. [in Python using json module](https://www.w3schools.com/python/python_json.asp))

```python
import json, os
image_list = ["image/marker_1.tif","image/marker_2.tif","image/marker_3.tif"]

with open("myproject.tmap","r") as f:
    tmap_project = json.load(f)
for image in image_list:
    tmap_project["layers"].append(
        {
            "name": os.path.basename(image), 
            "tileSource": image+".dzi"
        }
    )
with open("myproject_layers.tmap","w") as f:
    json.dump(tmap_project, f, indent=4)
```

**Comment by andrewjUTSW** [comment]
Awesome, thanks! Works great.
