### ISSUE TITLE
Feature Request: Additional metadata on reads

### ISSUE THREAD

**Issue by arundasan91** [TissUUmaps/TissUUmaps#2]
Hello!

Wondering if you all can integrate another drop-down menu to select a column of metadata to view per row in the input csv files. When we click on each read rendered on the screen, we now get the "key" in which we grouped by. For example, if we are grouping by the cell-type of a cell, we get that cell-type as the "key" visualized on the screen when we click on a particular read. 

I am wondering if there is an easy way to integrate additional metadata information to each mouse clicks on an individual read. This will help us tremendously moving forward. I hacked my way through and customized [glUtils.js](https://github.com/arundasan91/TissUUmaps/blob/master/tissuumaps/static/js/utils/glUtils.js#L1033-L1040) in `static/js/utils/` 
 to print what I wanted. Would be amazing to do it right from the app.

Thanks,
Arun

**Comment by arundasan91** [comment]
That would be great, thank you!
________________________________

**Comment by cavenel** [comment]
Hi Arun,
Could you test version 3.0.6? I added a "tooltip format" input in Advanced options.
You can use the following keywords in the input

- `{key}` to display the marker group
- `{name}` to display the second column of the marker table
- `{index}` to display the marker index in the csv file
- `{tab}` to display the tab name
- `{col_COLUMN}` to display any value from a given column "COLUMN" of the csv file.

For example, you could use a string like: `{tab} - {key}: {index} / {col_barcode}` that would output `Genes - EpCAM: 20067 / AGTGGGGAG`

**Comment by arundasan91** [comment]
Hi @cavenel 

Version 3.0.6 works perfect! Is there a way to save this format as a default so that we don't have to enter it every new launch?

Thanks!

**Comment by cavenel** [comment]
Hi @arundasan91,

You could create a button for a particular dataset, which will save all settings inside the tmap project.
(See https://github.com/TissUUmaps/TissUUmapsCore/issues/13#issuecomment-1049071288 for more details, and a video is coming soon with detailed instructions)
We don't have global settings saved yet.

I will close this issue if the new format answers your initial question!
