### ISSUE TITLE
Issue loading TissUUmaps

### ISSUE THREAD

**Issue by Boehmin** [TissUUmaps/TissUUmaps#20]
I get the following message when trying to load tissuumaps from terminal following the installation instructions:
```
INFO:root: * TissUUmaps version: 3.1.0.8
Traceback (most recent call last):
  File "/Users/boehm0002/.conda/envs/tissuumaps_env/bin/tissuumaps_server", line 5, in <module>
    from tissuumaps.__main__ import main
  File "/Users/boehm0002/.conda/envs/tissuumaps_env/lib/python3.9/site-packages/tissuumaps/__init__.py", line 100, in <module>
    from . import views
  File "/Users/boehm0002/.conda/envs/tissuumaps_env/lib/python3.9/site-packages/tissuumaps/views.py", line 298, in <module>
    @app.before_first_request
AttributeError: 'Flask' object has no attribute 'before_first_request'
```
I`m running this on the following machine:
MacBook Pro: Ventura 13.3.1 (a)
Chip: Apple M1 Max (32GB)

Many thanks for your help!

**Comment by cavenel** [comment]
Thank you for signaling that bug. It seems like `before_first_request` has been removed from last version of Flask.
I will fix the issue in the next release.
For now, you can fix it locally by installing a previous version of flask:
`pip install Flask==2.2.4`
Then TissUUmaps should run correctly.

**Comment by Boehmin** [comment]
Thank you so much - the error message disappeared and after quitting my session and reopening the terminal the user interface loaded!!

This might also be useful to know, if I try start TissUUmaps in Chrome (it works fine in Safari) I get the following error message:
"Access to 127.0.0.1 was deniedYou don't have authorisation to view this page.
HTTP ERROR 403"

**Comment by cavenel** [comment]
I will close this issue as the deprecated function has now been removed in version 3.1.1 (see https://github.com/TissUUmaps/TissUUmaps/commit/ca90c14326d53fdc224030ad80e135cf014572da) that was just released.

Could you maybe open a new specific issue for the problem in Chrome? Chrome should definitely be supported, and the error seems strange. Would be worth fixing!

Thanks :)

**Comment by Boehmin** [comment]
It seems to work now - I had to do a forced security update (managed University laptop). I`ll leave it until I can reproduce the problem again.
