### ISSUE TITLE
Problem with running Jupyter version in Docker

### ISSUE THREAD

**Issue by TKempchen** [TissUUmaps/TissUUmaps#21]
Hi,
I currently try to run the Jupyter version of TissUUmaps inside a Docker image, to use the inline display as part of a larger pipeline. I managed to install TissUUmaps as well as all dependencies and executed the example code shown in the documentation to summon the inline window. I have done this successfully outside of Docker. However, If I execute the function inside the Jupyter Notebook in Docker I only see a blank screen (no error message etc.). Has someone tried something similar and maybe knows what to do to avoid this issue? 
Thank you for your help!

This is what I tried: 
```
import os
import tissuumaps.jupyter as tj

# filepaths to images
tif_filepaths_list = ["i1","i2",...]

# filepath to csv
csv_path = "example.csv"

# start TissUUmaps
tj.loaddata(images= tif_filepaths_list, 
                            csvFiles=[csv_path], 
                            xSelector='x', 
                            ySelector='y', 
                            keySelector="leiden_0.4", 
                            nameSelector=None, 
                            colorSelector=None, 
                            piechartSelector=None, 
                            shapeSelector=None, 
                            scaleSelector=None, 
                            fixedShape=None, 
                            scaleFactor=1, 
                            colormap=None, 
                            compositeMode='source-over', 
                            boundingBox=None, 
                            port=5100, 
                            host='localhost', 
                            height=1000, 
                            tmapFilename='_project', 
                            plugins=[])
```

Output:
```
Creating project file /home/jovyan/_project.tmap
Loading url:  http://localhost:5100/_project.tmap?path=home/jovyan


<tissuumaps.jupyter.TissUUmapsViewer at 0x7f5c4ce224c0>
```

Here are my session infos:
-----
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) [GCC 10.3.0]
Linux-5.10.104-linuxkit-x86_64-with-glibc2.35

**Comment by TKempchen** [comment]
I was able to solve the issue by exposing both ports to the host system (8888 for Jupyter and 5100 for TissUUmaps). The problem was that Jupyter ask for the 5100 port of the host machine and not for the one of the container. 

Maybe this helps others if they encountered the same problem :)

**Comment by cavenel** [comment]
Thank you! Definitely something worse adding to documentation, I will add it for next update of doc.
