### ISSUE TITLE
Creation of docker/singularity containers

### ISSUE THREAD

**Issue by sebgoti** [TissUUmaps/TissUUmaps#27]
Hi @cavenel & team, I would like to launch Tissuumaps within Jupyter notebooks in order to use it on any HPC cluster (in many cases this do not have any type of GUI, though it can be possible to launch notebooks). My question would be, before trying to attempt this, whether you think it might work since some packages like PyQT6 seem to not be possible to install inside an environment of the cluster without any GUI. Do you have any experience with this, do you think it can be managed?

**Comment by cavenel** [comment]
Hi @sebgoti,
Yes, you can definitely install TissUUmaps without a GUI. Actually, the docker container that already exists (https://tissuumaps.github.io/TissUUmaps-docs/docs/sharing/docker.html) comes without GUI or any PyQt6 dependency.
But the simplest if you plan to use it within a jupyter notebook, is to install it with pip:
`pip install TissUUmaps` will install without GUI and PyQt6 dependencies, while `pip install TissUUmaps[full]` will install the GUI.
You can then use the TissUUmaps package from within the notebook in the same Python kernel:
```python
import tissuumaps.jupyter as tj
viewer = tj.loaddata(["image.png"])

viewer.screenshot()
```
