### ISSUE TITLE
Saving/Exporting High-Res Figures

### ISSUE THREAD

**Issue by arundasan91** [TissUUmaps/TissUUmaps#3]
Hello,

Hope you all are doing well!

I've been spending a lot of time with the new 3.0.6.x and 3.0.7.1 versions of TissUUmaps. I saw that there is a Capture Viewport option under Files which can save the screen as a png file. However, the resolution is not good enough for our use-case and for some reason it always produces an image which is rescaled to the top left of the entire saved image. Please see attached.

![TissUUmaps_capture (1)](https://user-images.githubusercontent.com/14352842/157317909-1760ab69-eda6-4753-8ad8-2df34a7a8935.png)

Also, I tried to save the content as a static webpage and got the following error:

```


INFO:root: * TissUUmaps version: 3.0.7.1
Starting port detection
Ending port detection 5000
 * Serving Flask app 'tissuumaps' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:34] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/d3-plugins/d3-scale-chromaticV3.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/d3/d3.v4.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/bootstrap-5.1.1/dist/css/bootstrap.min.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/chosen/chosen.jquery.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/chosen/chosen.min.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/jquery-3.5.1/jquery-3.5.1.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/bootstrap-icons-1.5.0/bootstrap-icons.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/css/style.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/bootstrap-5.1.1/dist/js/bootstrap.bundle.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/openseadragon-bin-3.0.0/openseadragon.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/openseadragon-plugins/openseadragon-scalebar.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/CamanJS-4.1.2/dist/caman.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/openseadragon-plugins/openseadragon-filtering.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/PapaParse-5.0.2/papaparse.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/openseadragon-plugins/openseadragon-svg-overlay.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/vendor/sorttable/sorttable.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/interfaceUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/markerUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/dataUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/OSDViewerUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/HTMLElementUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/regionUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/geometryUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/overlayUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/filterUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/glUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/pluginUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/utils/projectUtils.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/tmapp.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/js/flask.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:35] "GET /static/misc/uulogowhitetuum.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:36] "GET /static/vendor/bootstrap-icons-1.5.0/fonts/bootstrap-icons.woff2?856008caa5eb66df68595e734e59580d HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:37] "GET /static/misc/markershapes.png HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [08/Mar/2022 10:24:37] "GET /favicon.ico HTTP/1.1" 200 -
png
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/Users/arundas/opt/anaconda3/envs/tissuumaps-env-new/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/arundas/opt/anaconda3/envs/tissuumaps-env-new/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/arundas/opt/anaconda3/envs/tissuumaps-env-new/lib/python3.9/site-packages/tissuumaps/gui.py", line 373, in openImageThread
    os.startfile(os.path.normpath(path))
AttributeError: module 'os' has no attribute 'startfile'
[1]    58543 abort      tissuumaps
```

Some questions:
    1. Is there a way to save PDF or other lossless vector formats.
    2. Is there a way to interface TissUUmaps with Jupyter Lab's so that I can extract the graphs there? (I saw some examples but couldn't make it work).
    3. The error `AttributeError: module 'os' has no attribute 'startfile'` is due to Windows vs. Linux/Mac issues: https://stackoverflow.com/q/29823028/1869715. Could you please verify and fix? 

Thanks,
Arun

**Comment by cavenel** [comment]
Hi @arundasan91,

Unfortunately, we do not provide easy way to export the whole image in raw quality with markers. Only the visible viewport. The bug with os.startfile should be fixed with https://github.com/TissUUmaps/TissUUmaps/commit/0869cd50c860c1fdef1e7c670811c63861692200, available from v3.0.7.3: https://github.com/TissUUmaps/TissUUmaps/releases/tag/3.0.7.3

It is possible to start TissUUmaps from Jupyter Lab, but you will need some things to make it work. Maybe open a separate issue for this? Note that TissUUmaps will be loaded in an iFrame, so you won't have access to the graphs directly.

**Comment by arundasan91** [comment]
Thanks for the comments. Could you please list the file extensions supported for the visible viewport based saving functions?

**Comment by cavenel** [comment]
If I understand your question, saving the viewport from the application will save as a png file only.

**Comment by arundasan91** [comment]
Thanks. Does the markers support any type of rasterization when saved as png?

**Comment by cavenel** [comment]
The "viewport capture" should save exactly what you see on the screen, it's a bit like a screen capture of the inside of the viewport. So it will have the same rasterization as the one on the screen.
With the webgl canvas display, it is a bit difficult to make lossless capture of the whole image.
The bug you have where everything is rescaled to the top left of the entire saved image is weird though, and I think I saw it before on some Mac computer. I will check.

**Comment by arundasan91** [comment]
Thank you for looking into it. We're trying to see how we can produce publication worthy images (svg, eps, pdf, etc formats) with Tissuumaps. I wonder how you guys pull it off. Is there anything I am missing? I am really enjoying Tissuumaps as a visualization software for our various projects but the export capabilities are our greatest bottleneck right now. I'm also screen grabbing now. I later though of integrating Tissuumaps with python but you mentioned it will be an Iframe inside Jupiter without integrations with matplotlib. I'm curious to see how people export results from Tissuumaps.

Thanks again, 
Arun

**Comment by cavenel** [comment]
Hi @arundasan91,

One thing you can try to export in a higher resolution, is to zoom out the viewer. In Windows, press Ctrl+Mouse wheel down.
You will then get all the interface (buttons etc.) really small. Then select a view of interest, and take a capture (File > Capture Viewport).
The image should then be of higher resolution (up to 3 times the original resolution).
It is not vectorial format yet, but it should be enough for a paper figure.

**Comment by cavenel** [comment]
Version 3.0.8.2 should fix the bug of half size capture (previous version were not using the pixel ratio of the screen).

It also adds an option to change the resolution when capturing viewport. 5 times bigger gives a good quality output which I think is enough for publication! Unfortunately more than 5 fails to render all marker properly on my computer.

Before vs After:
![image](https://user-images.githubusercontent.com/6164758/161327539-0723fab4-70a7-4916-9117-94e52d08fc4c.png)

Let me know if this helps, and if I can close this issue

**Comment by arundasan91** [comment]
Hi @cavenel , the new capture works perfect! Thanks again for the good work and responding to our requests.
