### ISSUE TITLE
Marker filtering broken

### ISSUE THREAD

**Issue by jwindhager** [TissUUmaps/TissUUmaps#31]
![image](https://github.com/TissUUmaps/TissUUmaps/assets/7105759/3c132f88-d3ee-4deb-939a-38738130dd4f)

... happens because filtering is done on the whole row, not just on `/obs/gene`, which also includes all marker shapes in the dropdown.

**Comment by cavenel** [comment]
Should be fixed by https://github.com/TissUUmaps/TissUUmaps/commit/6956caa98fe09e96d44b1cb3b4d77d6771ba0020 and will be part of v3.1.1.6, I'll close the issue once it's released!
