### ISSUE TITLE
All links to Github are broken on website

### ISSUE THREAD

**Issue by smith6jt-cop** [TissUUmaps/TissUUmaps#32]
Link to Windows installation instructions does not work.  Link to Github issues does not work.  Are there instructions for installing on Windows anywhere?

**Comment by cavenel** [comment]
Thank you, I see that GitHub blocks links inside s frame indeed.
You can use this link while I fix this : https://tissuumaps.github.io/TissUUmaps-docs/docs/intro/installation.html

**Comment by cavenel** [comment]
Fixed now on the webpage also: https://tissuumaps.github.io/installation/
