### ISSUE TITLE
Issue/Doubt about the anchor location for plotting genes/cells

### ISSUE THREAD

**Issue by arundasan91** [TissUUmaps/TissUUmaps#4]
Hello,

Hope you all are doing well.

I have two csv files. Both has X and Y locations for genes. In one csv file some of the genes were removed as part of our preprocessing pipeline. I tried to visualize the two csv's after opening them in two tabs. However, now the two csv files doesn't match spatially. I checked the coordinates of the genes on both csv in TissUUmaps and they both match. However, they are plotted with a shift in both X and Y directions. I am attaching a few screenshots. Black dots are the processed genes and green stars are the raw reads. We can clearly see a spatial shift in TissUUmap visualization and the same X-Y coordinates for the same set of genes. 

My question is about how TissUUmaps finds the (0,0) location/anchor for plotting; and whether we can specify a common anchor for multiple tabs we are visualizing.

I am using TissUUmaps version: 3.0.7.1; installed via pip.

Thank you,
Arun

Case 1: 
![shifted_x_y_tmap](https://user-images.githubusercontent.com/14352842/158700329-6d56b454-9694-45ce-acf4-1695a47ccbd1.png)

Case 2:
![shifted_x_y_tmap2](https://user-images.githubusercontent.com/14352842/158700332-20168a70-ba5b-4010-b9d6-57b43b41e0e7.png)

Case 3:
<img width="357" alt="shifted_x_y_tmap3" src="https://user-images.githubusercontent.com/14352842/158700851-0c47227a-9e5a-42aa-9b76-7a8e6cdc6be5.png">

**Comment by cavenel** [comment]
Hi,

That's a very interesting bug, that could need some work. I will investigate a bit on how multiple csv files are displayed when there is no image under. I will let you know!

**Comment by arundasan91** [comment]
Thanks @cavenel, I can confirm that the fix works!
