### ISSUE TITLE
Opacity and visibility in GUI restarted

### ISSUE THREAD

**Issue by Andrea-Behanova** [TissUUmaps/TissUUmaps#46]
Opacity and visibility in GUI restart after adding a new filter, but the value inside the code is not changed.

**Comment by cavenel** [comment]
I just pushed a fix (https://github.com/TissUUmaps/TissUUmaps/commit/a63b28d1d8a018bbbd850525c9292689246b49af) in the 3.2 branch, so it should work in the next release!
