### ISSUE TITLE
Image Intensity Discrepancies

### ISSUE THREAD

**Issue by AnaSolbas** [TissUUmaps/TissUUmaps#57]
As I mentioned via email, my team has observed some discrepancies in intensity and contrast when uploading GSE206391 human skin tissue images (https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE206391) in TissUMapps. The images appear to exhibit higher levels of reds when viewed in TissUMapps compared to when we use other programs such as QUPath or Windows Photo Viewer. 

Following your recommendations, we have tried versions 3.2.0.4 and 3.2.1.4, but the issue persists.

<img width="1410" alt="v3_2_1_4-GSM6252915_2-V19S23-004-V1" src="https://github.com/TissUUmaps/TissUUmaps/assets/147802369/e8883874-868b-4fd3-835b-294f2f555d98">
<img width="1198" alt="v3_2_0_4-GSM6252915_2-V19S23-004-V1" src="https://github.com/TissUUmaps/TissUUmaps/assets/147802369/6c63e827-0488-4b45-a48f-b2014c8452c7">

**Comment by cavenel** [comment]
Hi, and thank you for opening an issue about this! 

Can you check that you don't have the temporary tiff file created by TissUUmaps still present in the image folder? For that, remove the `.tissuumaps` folder next to the original jpg image, and then load the jpg image in the new version of TissUUmaps. 
Let me know if it helps!

**Comment by AnaSolbas** [comment]
We have followed your instructions and removed the .tissuumaps file, and the problem is now fixed with the newest release of TissUUMaps. 

Thank you for your assistance in resolving this issue!
