### ISSUE TITLE
SVG vector graphics

### ISSUE THREAD

**Issue by TdzBAS** [TissUUmaps/TissUUmaps#65]
Hi,

I recognized that one can only save the capture viewport as a png file. For high quality publications scalable vector graphics would be essential (svg). Otherwise I experience a huge quality drop after loading into adobe illustrator for instance. 

Best,
Tolga

**Comment by cavenel** [comment]
Hi,

This is the same issue as https://github.com/TissUUmaps/TissUUmaps/issues/3
The solution in TissUUmaps is to use a bigger resolution factor when capturing viewport (4, 8, etc.).
It is still not vectorial, but unfortunately we can not export in SVG for now, and it should be good quality for publication.
