### ISSUE TITLE
Editing ROIs in TissUUmaps

### ISSUE THREAD

**Issue by linjing-fang** [TissUUmaps/TissUUmaps#68]
Dear TissUUmaps team,  

Thank you for developing such an amazing piece of software—it has been tremendously helpful for interactively visualizing my data.  

While creating Regions, I noticed that there doesn’t seem to be a way to edit an imported ROI or one drawn with TissUUmaps. I was wondering if I might have missed something. If not, could you suggest any possible workarounds? Additionally, is this a feature that might be implemented in the future?  

Thank you for your time and support!  

Best regards,  
Lynn

**Comment by cavenel** [comment]
Dear Lynn,

There is only one way to edit a region currently in TissUUmaps, by selecting the region you want to edit and using the "Brush based drawing". Then you can add (or remove by pressing shift) from the region.
Eventually we will add also point based editing and moving of regions, but this will be for a later version.

You can also merge and cut multiple regions, which can be used to edit regions.

Christophe

**Comment by linjing-fang** [comment]
> Dear Lynn,
> 
> There is only one way to edit a region currently in TissUUmaps, by selecting the region you want to edit and using the "Brush based drawing". Then you can add (or remove by pressing shift) from the region. Eventually we will add also point based editing and moving of regions, but this will be for a later version.
> 
> You can also merge and cut multiple regions, which can be used to edit regions.
> 
> Christophe

I see. Awesome. Thank you for your prompt help! 

Best,
Lynn
