### ISSUE TITLE
Empty string in the key column gives strange behaviour

### ISSUE THREAD

**Issue by cavenel** [TissUUmaps/TissUUmaps#8]
When the first row of a csv file contains an empty value in the **Key to group by** column, it shows inconsistent results in the marker table. Either 0, or undefined, or 0,0,0,0,0,0,0,0...0,0,0,0, or empty, depending on the number of rows with empty keys.

I believe the Papa Parse library is to blame here. @FredrikNysjo could you have a look?

Here is a csv file to reproduce all behaviours:
[celltype_Rayon2021.csv](https://github.com/TissUUmaps/TissUUmaps/files/9298479/celltype_Rayon2021.csv)
Which gives:
![image](https://user-images.githubusercontent.com/6164758/183861827-667dcc3d-87d7-4801-931b-bb3126d11393.png)
Expected behaviour:
![image](https://user-images.githubusercontent.com/6164758/183861963-699d0846-7d39-4a06-93d2-08ae298faf0e.png)

And here is a minimal example with two different displayed values for empty column:
```
x,y,target
0,0,
0,1,"not empty"
1,1,
```
![image](https://user-images.githubusercontent.com/6164758/183863730-33fc8ea3-2b69-4e6d-9dea-ec6d3595ed0d.png)

**Comment by FredrikNysjo** [comment]
Fixed in commit 5fb3099. Empty values are now treated as strings when checking if a column is numerical.
